### ISSUE TITLE
Global option to set delay time

### ISSUE THREAD

**Issue by ankurk91** [andrepolischuk/messg#6]
Hi, @andrepolischuk
Thanks for the most lightweight notification library.

I was trying to set the **delay** time globally.
```js
window.messg = require('messg');
messg.delay = 5000;
```
But i think it is not possible, can you please add such option so that if we don't specify a delay then it can take delay from global config and auto hide after that time.
```js
messg.error('You need to be logged-in first.');
```

**Comment by andrepolischuk** [comment]
Thanks for proposal. Done. Published as 2.2.0.
