### ISSUE TITLE
Callback when message with delay is clicked

### ISSUE THREAD

**Issue by aldebaran798** [andrepolischuk/messg#7]
Hi! congratulations for your project.

Is possible call a function when a message is clicked, but not fire the function when delay option auto-hide the message?

**Comment by andrepolischuk** [comment]
Currently you can attach callback for close message without buttons:

```js
messg('Hello').hide(() => {
  // ...
})
```

or attach callbacks for click on buttons:

```js
messg('Hello').button('Ok', () => {
  // ...
})
```

**Comment by aldebaran798** [comment]
Thank you!
